version: "3.8"

services:
  wa-transfer:
    build: .
    container_name: wa-transfer
    stdin_open: true
    tty: true
    volumes:
      - ./creds:/app/creds
    environment:
      - NODE_ENV=production
